services:
  - type: web
    name: aeronexis
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && CI=false npm run build && cd ..
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /v1/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: API_KEY_SECRET
        value: apix-demo-key-2026

